Ac 723 appliance
anbox-cloud/discourse-docs pull request #104
Opened 2022-03-18 12:26 UTC by ru-fu

Some more clarifications to differentiate between the full Anbox Cloud deployment and the appliance.

2022-03-24 10:05 UTC, adglkh requested changes

2022-03-24 12:41 UTC, morphis approved these changes
LGTM, thanks!

2022-03-24 13:12 UTC, ru-fu commented on howto/manage/manage-appliance.md
> +  Expose or unexpose the HTTP API of the stream gateway and manage access to it. If the HTTP API is exposed (which is the default), authenticated clients can connect to it. Authentication requires an
Thanks - updated.

2022-03-25 00:59 UTC, adglkh commented
LGTM

2022-03-25 01:02 UTC, adglkh approved these changes

2022-03-25 09:35 UTC, merged