Clean up GPU support page
anbox-cloud/discourse-docs pull request #167
Opened 2022-09-15 09:47 UTC by ru-fu

Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>

2022-09-15 11:16 UTC, morphis requested changes

2022-09-15 11:16 UTC, morphis commented on exp/gpu-support.md
>  | Nvidia | Quadro, Tesla  | Yes    | Yes                   |
While we're on it we need to clean this up. For NVIDIA we should say `Quadro, Tesla, Ampere`

2022-09-15 11:16 UTC, morphis commented on exp/gpu-support.md
> +AMS configures each LXD container to pass through a GPU device from the host. As of right now, all GPUs that are available to a machine are passed to every container that owns a GPU slot. For Nvidia
```suggestion
AMS configures each LXD container to pass through a GPU device from the host. As of right now, all GPUs that are available to a machine are passed to every container that owns a GPU slot. For NVIDIA GPUs, LXD uses the [NVIDIA container runtime](https://github.com/NVIDIA/nvidia-container-runtime) to make the GPU driver of the host available to the container.
```

2022-09-15 11:16 UTC, morphis commented on exp/gpu-support.md
>  | Nvidia | Quadro, Tesla  | Yes    | Yes                   |
```suggestion
| NVIDIA | Quadro, Tesla  | Yes    | Yes                   |
```

2022-09-15 11:16 UTC, morphis commented on exp/gpu-support.md
>  Anbox Clouds allows access to GPUs from Intel, AMD and Nvidia inside the Anbox container. Concrete support for the individual GPU depends on the platform being using for Anbox. The included `webrtc`
```suggestion
Anbox Clouds allows access to GPUs from Intel, AMD and NVIDIA inside the Anbox container. Concrete support for the individual GPU depends on the platform being using for Anbox. The included `webrtc` platform currently supports the following GPUs:
```

2022-09-15 11:48 UTC, ru-fu commented on exp/gpu-support.md
> +If no GPU is available, Anbox Cloud automatically falls back to software rendering and video encoding. This makes it possible to run entirely without a GPU.
Yes - that's the `--enable-graphics` flag, correct?
Tried to clarify it. :)

2022-09-15 11:48 UTC, ru-fu commented on exp/gpu-support.md
> +AMS configures each LXD container to pass through a GPU device from the host. As of right now, all GPUs that are available to a machine are passed to every container that owns a GPU slot. For Nvidia
Fixed globally (in a separate commit).

2022-09-16 08:14 UTC, morphis commented on exp/gpu-support.md
> +If no GPU is available, Anbox Cloud automatically falls back to software rendering and video encoding. This makes it possible to run entirely without a GPU.
Yes, it is.

2022-09-16 08:14 UTC, morphis commented on exp/gpu-support.md
> +AMS configures each LXD container to pass through a GPU device from the host. As of right now, all GPUs that are available to a machine are passed to every container that owns a GPU slot. For Nvidia
Thanks!

2022-09-16 08:15 UTC, morphis approved these changes
LGTM

2022-09-16 09:04 UTC, merged