add a security page
anbox-cloud/discourse-docs pull request #170
Opened 2022-10-03 08:12 UTC by ru-fu

Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>

2022-10-03 08:12 UTC, ru-fu commented on exp/security.md
> +| Verified Boot                              | -                        |
Need to check and fill the question marks (or actually, the full table ;) ).

2022-10-06 11:51 UTC, morphis requested changes

2022-10-06 14:13 UTC, ru-fu commented on exp/security.md
> +In addition, to ensure that the latest Ubuntu security patches are applied outside of image updates as well, Anbox Cloud checks for and installs available security updates every time an application i
Please check again, not 100% sure I understood your comment correctly. ;)

2022-10-07 15:26 UTC, morphis commented on exp/security.md
> +While containers are fully isolated, all containers currently use the same GPU resources. As a result, a container could take all GPU resources in a DDoS-like attack, which would prevent other contai
Alright, lets leave that out then

2022-10-07 15:26 UTC, morphis approved these changes
LGTM, thanks!

2022-10-10 07:15 UTC, merged