add information about image support
anbox-cloud/discourse-docs pull request #193
Opened 2023-01-06 14:09 UTC by ru-fu

Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>

2023-01-09 08:00 UTC, morphis requested changes

2023-01-09 08:00 UTC, morphis commented on ref/provided-images.md
> +Deprecations are announced at least one release in advance.
I think two releases in advance (so 6 months) is good.

2023-01-11 08:54 UTC, morphis approved these changes
LGTM

2023-01-12 08:37 UTC, ru-fu commented on ref/provided-images.md
> +Anbox Cloud provides images based on two different Ubuntu versions, currently 18.04 (bionic) and 22.04 (jammy). The bionic images are deprecated and will receive their last update with the Anbox Clou
Removed the sentence.

2023-01-13 10:26 UTC, merged