Add note to discourage using LXD commands
anbox-cloud/discourse-docs pull request #211
Opened 2023-02-16 11:30 UTC by keirthana

Add a note to discourage the use of `lxd` commands to start and stop a container and recommend use of `amc` commands only.

2023-02-16 15:36 UTC, morphis requested changes

2023-02-16 15:36 UTC, morphis commented on howto/container/start.md
> +Do not use the `lxd` command to start a container. Always use the `amc` command instead. Anbox Cloud containers have their own lifecycle and using the `lxd` command to start a container can cause the
```suggestion
Do not use the `lxc` command to manage a container. Always use the `amc` command instead. Anbox Cloud containers have their own lifecycle and using the `lxc` command to manage a container can cause the container to be out of sync.
```

2023-02-16 15:36 UTC, morphis commented on howto/container/stop.md
> +Do not use the `lxd` command to stop a container. Always use the `amc` command instead. Anbox Cloud containers have their own lifecycle and using the `lxd` command to stop a container can cause the c
See above

2023-02-17 01:02 UTC, adglkh approved these changes
Thanks.
LGTM

2023-02-17 09:43 UTC, ru-fu approved these changes
Looks good! :)

2023-02-17 09:43 UTC, ru-fu commented on howto/container/start.md
> +Do not use the `lxc` command to manage a container. Always use the `amc` command instead. Anbox Cloud containers have their own lifecycle and using the `lxc` command to manage a container can cause t
```suggestion
Do not use the `lxc` command to manage a container. Always use the `amc` command instead. Anbox Cloud containers have their own life cycle and using the `lxc` command to manage a container can cause the container to be out of sync.
```
Same below - then the spell checker should be happy. :)

2023-02-17 14:02 UTC, morphis approved these changes

2023-02-17 14:04 UTC, merged