Add architecture terms to glossary
anbox-cloud/discourse-docs pull request #223
Opened 2023-04-04 12:00 UTC by keirthana

2023-04-04 12:40 UTC, ajanon approved these changes
LGTM!

2023-04-05 01:18 UTC, adglkh requested changes

2023-04-05 01:18 UTC, adglkh commented on ref/glossary.md
> +A set of LXD servers that share the same distributed database that holds the configuration for the cluster members and their instances.
LXD servers
->
LXD nodes

2023-04-05 01:18 UTC, adglkh commented on ref/glossary.md
> +### Control node
Is this `Control node` the management node that we described below? If so, let's be consistent in the way we use terms on this page.

2023-04-05 01:18 UTC, adglkh commented on ref/glossary.md
> +The group of components that is made up of the management layer (AMS, AMC, etcd), control node, LXD, AMS node controller.
I am not quite sure if we wanna mention the control node here next to `the management layer` as they seem to be the same to me.

2023-04-06 01:06 UTC, adglkh approved these changes
LGTM

2023-04-06 07:06 UTC, morphis approved these changes
LGTM

2023-04-06 07:07 UTC, merged