Document the feature `android.allow_custom_android_id`
anbox-cloud/discourse-docs pull request #231
Opened 2023-05-02 15:01 UTC by adglkh

2023-05-02 16:31 UTC, keirthana requested changes
Minor comments from me, if these are addressed, I am good.

2023-05-02 16:31 UTC, keirthana commented on ref/ams-configuration.tmpl.md
> +To enable the Android container to use a custom Android ID, add the feature `android.allow_custom_android_id` upon application creation. An system app can influence the Android ID of one specific app
```suggestion
To enable the Android container to use a custom Android ID, add the feature `android.allow_custom_android_id` upon application creation. A system app can influence the Android ID of a specific app during the Android runtime by setting the system property in the format of:
```

2023-05-02 16:31 UTC, keirthana commented on ref/ams-configuration.tmpl.md
> +To enable the Android container to use a custom Android ID, add the feature `android.allow_custom_android_id` upon application creation. An system app can influence the Android ID of one specific app
I am not really sure but should it read:

> To enable the Android container to use a custom Android ID, add the feature _flag_ `android.allow_custom_android_id` upon application creation.

2023-05-03 07:19 UTC, keirthana approved these changes
LGTM!

2023-05-03 11:51 UTC, morphis requested changes

2023-05-03 11:51 UTC, morphis commented on ref/ams-configuration.tmpl.md
> +  The `<index>` is a number in the range from 0 to 126.
We should explain the index a bit further so it's clear why it exists.

2023-05-04 14:34 UTC, morphis approved these changes
LGTM

2023-05-04 14:44 UTC, merged