Release specific doc updates
anbox-cloud/discourse-docs pull request #241
Opened 2023-05-16 09:38 UTC by keirthana

All release and version specific updates are grouped in this PR. There will be one more commit to this PR once the release notes is finalised. I have a couple more points and links to add to the release notes.

2023-05-16 10:13 UTC, ajanon requested changes

2023-05-16 10:13 UTC, adglkh requested changes

2023-05-16 10:13 UTC, adglkh commented on release-notes.md
> +    Choreographer: Frame time is 0.278502 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
Let's fold the above three lines into a single one:
* Fix the incorrect vsync timestamps in anbox hardware composer

2023-05-17 06:38 UTC, morphis requested changes

2023-05-17 06:38 UTC, morphis commented on component-versions.md
> +| `anbox-cloud-core` | `1.18/stable` | 83 |
The revisions will change when we run the `promote-bundles` job today. So these are not final.

2023-05-17 06:38 UTC, morphis commented on roadmap.md
> +* Bug fixes
Can you add the 1.19.0 item too

```
### 1.19.0 (August 2023)

Target date: August 16, 2023

* Pagination / filtering support for parts of the AMS API (containers + applications)
* AV1 hardware accelerated video encoding on NVIDIA GPUs
* OpenAPI based documentation of the AMS API
* Cgroupv1 compatiblity layer to support Android on cgroupv2-only systems
* Vulkan support for NVIDIA GPUs (alpha)

2023-05-17 06:54 UTC, adglkh approved these changes
LGTM

2023-05-17 06:56 UTC, ajanon approved these changes
LGTM

2023-05-17 06:59 UTC, adglkh approved these changes
LGTM

2023-05-17 07:24 UTC, ajanon commented on index.md
> +* Vulkan support for NVIDIA GPUs
Wait, isn't that only for 1.19?

2023-05-17 10:17 UTC, merged