Remove stream client howto topic
anbox-cloud/discourse-docs pull request #280
Opened 2023-07-28 09:33 UTC by keirthana

Move the content regarding SDKs in the howto guide of stream client and remove the topic.
Retaining the "How to access stream gateway" topic as it has a lot of additional information.

2023-07-28 09:49 UTC, ajanon requested changes
One nitpick

2023-07-28 09:49 UTC, ajanon commented on tut/stream-client.md
> +    always specify both the height and the width attributes-->
```suggestion
    <!--To display the video element correctly,
        always specify both the height and the width attributes-->
```
To make the text aligned. It's not necessary, I just think it looks a bit better, but I'm fine either way. What do you think?

2023-07-28 17:56 UTC, morphis approved these changes
LGTM, thanks!

2023-07-31 05:14 UTC, adglkh commented on howto/stream/access.md
> +### Using the token in your requests
Maybe simplified to `Using the token` to correlate with `Creating a token` in the above and `Deleting a token` below. To me, if we want to keep it as is, `Creating a token for your request` sounds more natural.

2023-07-31 09:01 UTC, adglkh approved these changes
LGTM

2023-07-31 10:37 UTC, merged