Create 1.19.1 release notes
anbox-cloud/discourse-docs pull request #296
Opened 2023-08-30 08:25 UTC by keirthana

Bug fixes and features list available at https://docs.google.com/spreadsheets/d/1b9EjtqM_odnEe3N6HW827ARqiRFyB4GMlGOMFJV-EhM/edit#gid=1522264433 along with notes.

Pending addition to release notes: https://warthogs.atlassian.net/browse/AC-1846

2023-08-30 09:06 UTC, ajanon requested changes

2023-08-30 09:06 UTC, ajanon commented on release-notes/1.19.1.md
> +* The security patch CVE-2023-21272 - A-227471459 in the [Android Security Bulletin - August 2023](https://source.android.com/docs/security/bulletin/2023-08-01) became available and is applied.<!--AC
```suggestion
```
So actually, we already had this patched in our trees, so there is no need to mention it: see the comment on AC-1803. I made sure that there was no `release-notes` label on that ticket.

I feel a bit bad asking you to remove this after you wrote it...
What do you think we could do to avoid this in the future? Should I have marked the JIRA ticket as 'Rejected'?

2023-08-30 09:39 UTC, keirthana commented on release-notes/1.19.1.md
> +* The security patch CVE-2023-21272 - A-227471459 in the [Android Security Bulletin - August 2023](https://source.android.com/docs/security/bulletin/2023-08-01) became available and is applied.<!--AC
My bad, I missed seeing the comment on this. Don't worry about it, that's why we have the review process to catch such things. I don't mind having to redo things because in documentation, you can't always avoid rework.

2023-09-04 02:30 UTC, adglkh commented on release-notes/1.19.1.md
> +* The Android WebView has been updated to 116.0.5845.93.
Our webview auto build job just bumped up and updated the webview to 116.0.5845.163 yesterday.
```
commit 9cf7b77dd5d750a41ece7b2bbcdadffdf1fdc8c5 (stable-1.19)
Author: Anbox Cloud Job Build Bot <anbox-cloud-jb-bot@canonical.com>
Date:   Sun Sep 3 09:38:17 2023 +0000

    feat(prebuilts): update Android Webview to 116.0.5845.163
```

2023-09-04 07:20 UTC, ajanon approved these changes
LGTM

2023-09-04 18:16 UTC, morphis approved these changes
LGTM, one suggestion.

2023-09-04 18:16 UTC, morphis commented on release-notes/1.19.1.md
> +* The Android WebView has been updated to 116.0.5845.163.
Should we link to https://chromereleases.googleblog.com/2023/08/chrome-for-android-update_02015057758.html?

2023-09-05 03:33 UTC, jat-canonical approved these changes
LGTM

2023-09-05 03:34 UTC, adglkh approved these changes
LGTM

2023-09-06 05:22 UTC, adglkh commented on release-notes/1.19.1.md
> +* Android security updates for September 2023 (see Android Security Bulletin - September 2023 for more information).
Android security updates for September 2023 (see Android Security Bulletin - September 2023 for more information).
->
Android security updates for September 2023 (see [Android Security Bulletin - September 2023](https://source.android.com/docs/security/bulletin/2023-09-01) for more information).

2023-09-06 05:24 UTC, adglkh commented on release-notes/1.19.1.md
> +* Android security updates for September 2023 (see Android Security Bulletin - September 2023 for more information).
Android security updates for September 2023 (see Android Security Bulletin - September 2023 for more information).
->
Android security updates for September 2023 (see [Android Security Bulletin - September 2023](https://source.android.com/docs/security/bulletin/2023-09-01) for more information).

2023-09-13 08:51 UTC, merged