Introduce `enable_anbox_ime` feature flag
anbox-cloud/discourse-docs pull request #78
Opened 2022-01-20 11:08 UTC by adglkh

2022-01-20 13:02 UTC, ru-fu requested changes

2022-01-20 13:02 UTC, ru-fu commented on reference/ams-configuration.md
> +The client-side virtual keyboard is disabled by default but can be enabled with the `enable_anbox_ime` feature flag. It requires the client application to embed [AnboxWebView](https://discourse.ubunt
```suggestion
The client-side virtual keyboard is disabled by default but can be enabled with the `enable_anbox_ime` feature flag. It requires the client application to embed [AnboxWebView](https://discourse.ubuntu.com/t/integrate-a-client-side-virtual-keyboard), which interacts with the client-side virtual keyboard for text editing and sends the text to the Android container.
```

2022-01-20 13:51 UTC, adglkh commented on howto/stream/client-side-keyboard.md
> +To enable the application running in the Android container can receive the texts sent from the client-side virtual keyboard, the feature `enable_anbox_ime` must be declared in the application manifes
yeah, not ideal. 
Maybe, after 
```
For the complete implementation details, refer to the `enhanced_webview_streaming` example in the `example/android` folder.
``` and before the  ` 1. Import the AAR library`
How do you think?

2022-01-20 13:51 UTC, adglkh commented on reference/ams-configuration.md
> +The client-side virtual keyboard is disabled by default but can be enabled with the `enable_anbox_ime` feature flag. It requires the client application to embed [AnboxWebView](https://discourse.ubunt
+1, Will fix.

2022-01-20 14:26 UTC, ru-fu commented on howto/stream/client-side-keyboard.md
> +To enable the application running in the Android container can receive the texts sent from the client-side virtual keyboard, the feature `enable_anbox_ime` must be declared in the application manifes
Yes, that's another place I was thinking about. Sounds good! :+1:

2022-01-21 08:29 UTC, ru-fu approved these changes
Looks good!

2022-01-21 12:56 UTC, merged